In [1]:
import numpy as np

In [3]:
a=[1,2,3,4,5,6,7,8,9,3]
array1=np.array(a)

In [5]:
print(array1)

[1 2 3 4 5 6 7 8 9 3]


In [6]:
print(type(array1))

<class 'numpy.ndarray'>


In [7]:
twoDarray=np.array([[1,2,3,4,5,6],[6,7,8,9,0,2],[5,6,8,9,3,5]])

In [8]:
print(twoDarray)

[[1 2 3 4 5 6]
 [6 7 8 9 0 2]
 [5 6 8 9 3 5]]


In [9]:
print(twoDarray.shape)

(3, 6)


In [10]:
one=np.ones((3,3))

In [11]:
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
zero=np.zeros((4,9))

In [15]:
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
a=np.arange(10,30,2)

In [19]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
rand=np.random.random(7)

In [21]:
rand

array([0.33676612, 0.70409708, 0.62893456, 0.03864291, 0.87412734,
       0.96863331, 0.95696934])

In [22]:
rand1=np.random.randn(3,6)

In [23]:
rand1

array([[-1.9319667 ,  1.69515912, -0.23893961,  0.78868062, -0.71939566,
         0.08383409],
       [ 1.88996857,  0.05252294, -1.03298424,  0.83641469,  0.39177023,
         0.20973413],
       [-2.1053261 ,  0.1110074 ,  1.53774394, -0.18344382, -0.03284853,
         0.24139811]])

In [26]:
twoDarray.reshape(2,-1)

array([[1, 2, 3, 4, 5, 6, 6, 7, 8],
       [9, 0, 2, 5, 6, 8, 9, 3, 5]])

In [33]:
%%timeit
twoDarray*twoDarray

1.56 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [32]:
twoDarray*twoDarray

array([[ 1,  4,  9, 16, 25, 36],
       [36, 49, 64, 81,  0,  4],
       [25, 36, 64, 81,  9, 25]])